name: Laravel Code Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Add Composer Global Bin to PATH
        run: echo "$HOME/.composer/vendor/bin" >> $GITHUB_PATH

      - name: Run PHP_CodeSniffer
        run: phpcs --standard=PSR12 app/
